all:
	make -C iftest
	make -C asynctst
	make -C smoketest
	make -C actcancel
	make -C evtest
	make -C inproc

clean:
	make -C iftest clean
	make -C asynctst clean
	make -C smoketest clean
	make -C actcancel clean
	make -C evtest clean
	make -C inproc clean

