//Generated by ridlc
//Your task is to implement the following classes
//to get your rpc server work
#pragma once
#include "StressTest.h"

class CStressSvc_CliImpl
    : public CStressSvc_CliSkel
{
    public:
    typedef CStressSvc_CliSkel super;
    CStressSvc_CliImpl( const IConfigDb* pCfg ) :
        super::virtbase( pCfg ), super( pCfg )
    {}

    /* The following two methods are important for */
    /* streaming transfer. rewrite them if necessary */
    gint32 OnStreamReady( HANDLE hChannel ) override
    { return super::OnStreamReady( hChannel ); } 
    
    gint32 OnStmClosing( HANDLE hChannel ) override
    { return super::OnStmClosing( hChannel ); }
    // IEchoThings
    virtual gint32 EchoCallback(
        IConfigDb* context, gint32 iRet,
        const std::string& strResp /*[ In ]*/ );
    
    virtual gint32 OnHelloWorld(
        const std::string& strMsg /*[ In ]*/ );
    
    gint32 IncMloop();
};

