/*
 * =====================================================================================
 *
 *       Filename:  parsrctx.h
 *
 *    Description:  declarations of classes for parser context
 *
 *        Version:  1.0
 *        Created:  05/08/2026 06:28:51 PM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Ming Zhi( woodhead99@gmail.com )
 *   Organization:
 *
 *      Copyright:  2026 Ming Zhi( woodhead99@gmail.com )
 *
 *        License:  Licensed under GPL-3.0. You may not use this file except in
 *                  compliance with the License. You may find a copy of the
 *                  License at 'http://www.gnu.org/licenses/gpl-3.0.html'
 *
 * =====================================================================================
 */

#pragma once

#include <vector>
#include <string>
#include <memory>
#include "nonterm.h"

#define CLEAR_RSYMBS \
for( int i = 0; i < ( yylen ); i++ ) \
    { yyvsp[ -i ].Clear(); }

#define DEFAULT_ACTION \
    yyval = yyvsp[ 1 - yylen ]; CLEAR_RSYMBS;

#include "rpc.h"

#define YYPUSH_ACCEPT       0 // Success / Input Accepted
#define YYPUSH_ABORT        1 // Parsing aborted
#define YYPUSH_NOMEM        2 // Syntax Error

// don't change this value manually. It will be automatically updated when stparser.cpp is generated by bison.
#define CONFLICT_STATE     377: case 426
// the state to replace TOK_MINUS with TOK_SUB
#define SUBEXPR_STATE     72
#define LVALUE_BIT_STATES     66: case 113: case 127: case 379
#define METHOD_RET_STATE     468
#define USING_SEP_STATE     97
#define CASESEL_CHECK_STATES     std::vector<int>({ 63, 82 })

#define YYSTYPE std::shared_ptr< YYSPAIR >

struct YYLTYPE1
{
  int first_line;
  int first_column;
  int last_line;
  int last_column;
};

#define YYLTYPE YYLTYPE1

struct YYLTYPE2 :
    public YYLTYPE
{
    stdstr text;
    gint32 fidx = -1; // file name index into the m_vecFiles.
    void initialize()
    {
        first_line = 1;
        first_column = 1;
        last_line = 1;
        last_column = 1;
    }

    YYLTYPE2( const YYLTYPE2& rhs )
    {
        first_line = rhs.first_line;
        first_column = rhs.first_column;
        last_line = rhs.last_line;
        last_column = rhs.last_column;
        text = rhs.text;
    }
    YYLTYPE2()
    {
        initialize();
        fidx = -1;
    }
};

namespace rpcf
{
typedef enum
{
    invalidProgress = -1,
    scanning = 0,
    building,
    leaving,
} enumCPProgress;

typedef enum
{
    firstBlock,
    elsifBlock,
    elseBlock,
    endifBlock,
} enumBlkType;

typedef std::pair< Variant, YYLTYPE2 > YYSPAIR;

struct FILECTX2
{
    FILE*       m_fp = nullptr;
    rpcf::Variant     m_oVal;
    std::string m_strPath;
    std::string m_strLastVal;
    YYLTYPE2    m_oLocation;

    FILECTX2();
    FILECTX2( const std::string& strPath );
    FILECTX2( const FILECTX2& fc );
    ~FILECTX2();
};

struct CondPragmaState
{
    enumCPProgress m_iProgress = scanning;
    enumBlkType m_iBlkType = firstBlock;
    gint32 m_iBlkIdx = 0;
    std::vector< YYLTYPE2 > m_vecBlockPos;

    // const expr value of m_iBlkIdx if m_iProgress is
    // scanning
    bool m_bExprValue = false; 

    // conditional depth in the block m_iBlkIdx
    gint32 m_iCondDepth = 0;
    CondPragmaState( int iProgress,
        int iBlkType, int iBlkIdx ) :
        m_iProgress( ( enumCPProgress )iProgress ),
        m_iBlkType( ( enumBlkType ) iBlkType ),
        m_iBlkIdx( iBlkIdx )
    {}

    CondPragmaState() {}
};
struct CTokenInfo
{
    YYLTYPE2 lloc;
    int token = -1;
    YYSTYPE pVal;

    CTokenInfo( const CTokenInfo& rhs )
    {
        lloc = rhs.lloc;
        token = rhs.token;
        pVal = rhs.pVal;
    }

    CTokenInfo( const YYLTYPE2& lloc,
        int token, YYSTYPE& pVal )
    {
        this->lloc = lloc;
        this->token = token;
        this->pVal = pVal;
    }

    CTokenInfo()
    {}
};

struct CTokenBuffer
{
    std::deque< CTokenInfo > m_queFuture;
    std::deque< CTokenInfo > m_queHistory;
    CTokenInfo m_oEmpty;

    CTokenBuffer()
    {}

    inline void PushToken( const CTokenInfo& oToken )
    { m_queFuture.push_back( oToken ); }
    inline void DequeToken()
    { 
        if( m_queFuture.empty() )
            return;
        m_queHistory.push_back(
            m_queFuture.front() );
        m_queFuture.pop_front();
        if( m_queHistory.size() > 10 )
            m_queHistory.pop_front();
    }

    inline const CTokenInfo& GetCurTok(
        guint32 idx = 0 ) const
    {
        if( idx < 0 || m_queFuture.size() <= idx )
            return m_oEmpty;
        return m_queFuture[ idx ];
    }

    inline const CTokenInfo& GetPrevTok(
        guint32 idx = 0 ) const
    {
        if( idx < 0 || m_queHistory.size() <= idx )
            return m_oEmpty;
        return m_queHistory[ idx ];
    }
    gint32 GetTokenCount() const
    { return m_queFuture.size(); }
};

struct CSTParserContext
{
    // conditional pragma state stack. Each element
    // represents a conditional pragma block, and the
    // top one is the current block being parsed.
    std::vector< CondPragmaState > m_vecCondStack;
    // the last pragma representing current non-main ps
    // is parsing.
    gint32 m_iLastPragma = nt_invalid;
    gint32 IsCondStackEmpty() const
    { return m_vecCondStack.empty(); }

    // the search paths for included files. The paths
    // are searched in order.
    std::vector< stdstr > m_vecInclPaths;
    std::vector< std::shared_ptr< FILECTX2 > > m_vecFileStack;
    void* m_yyscanner = nullptr;
    stdstr m_strCurFile;
    std::vector< stdstr > m_vecFiles;
    gint32 m_iLastCaseChk = 0;
    CTokenBuffer m_oTokens;

    CSTParserContext()
    {}

    void SetScanner( void* scanner )
    { m_yyscanner = scanner; }

    void* GetScanner()
    { return m_yyscanner; }

    gint32 GetCondStackSize() const
    { return m_vecCondStack.size(); }

    inline const CondPragmaState& GetTopState() const
    {
        static const CondPragmaState oInvalidState =
            { invalidProgress, 0, 0 };
        if( m_vecCondStack.empty() )
            return oInvalidState;
        return m_vecCondStack.back();
    }

    inline CondPragmaState& GetTopState()
    {
        static CondPragmaState oInvalidState =
            { invalidProgress, 0, 0 };
        if( m_vecCondStack.empty() )
            return oInvalidState;
        return m_vecCondStack.back();
    }

    inline void PushState(
        const CondPragmaState& cps )
    { m_vecCondStack.push_back( cps ); }

    inline void PopState()
    { m_vecCondStack.pop_back(); }

    inline gint32 GetLastPragma() const
    { return m_iLastPragma; }

    inline void SetLastPragma( gint32 iPragma )
    { m_iLastPragma = iPragma; }

    FILE* TryOpenFile(
        const std::string& strFile,
        stdstr& strFullPath );

    gint32 m_iError = 0;
    inline void IncError()
    { m_iError++; }

    inline gint32 GetErrorCount() const
    { return m_iError; }

    gint32 m_iSemErr = 0;
    inline void IncSemError()
    { m_iSemErr++; }

    inline gint32 GetSemErrorCount() const
    { return m_iSemErr; }

    gint32 GetFileIdx( const stdstr& strFile ) const;
    inline stdstr GetFileName( gint32 idx ) const
    {
        if( idx < 0 || idx >= m_vecFiles.size() )
            return stdstr( "" );
        return m_vecFiles[ idx ];
    }
    inline const stdstr& GetCurFileName() const
    { return m_strCurFile; }

    inline stdstr& GetCurFileName()
    { return m_strCurFile; }

    bool IsFileOnStack( const stdstr& strFile ) const;
    inline const CTokenInfo& GetCurTok(
        guint32 idx = 0 ) const
    { return m_oTokens.GetCurTok( idx ); }

    inline const CTokenInfo& GetPrevTok(
        guint32 idx = 0 ) const
    { return m_oTokens.GetPrevTok( idx ); }

    inline void DequeToken()
    { m_oTokens.DequeToken(); }

    inline void PushToken( const CTokenInfo& oToken )
    { m_oTokens.PushToken( oToken ); }

    gint32 GetTokenCount() const
    { return m_oTokens.GetTokenCount(); }
};


}

extern std::shared_ptr< rpcf::CSTParserContext > g_pParserCtx;
inline rpcf::CSTParserContext* GetParserCtx()
{ return g_pParserCtx.get(); }

