// Generated by ridlc
// ../../ridl/.libs/ridlc -sO . ./appmon.ridl 
// Your task is to implement the following classes
// to get your rpc server work
#pragma once
#include "appmon.h"

#define Clsid_CSimpleAuth_CliBase    Clsid_Invalid

DECLARE_AGGREGATED_PROXY(
    CSimpleAuth_CliBase,
    CStatCounters_CliBase,
    IIUserManager_CliApi,
    CFastRpcProxyBase );

class CSimpleAuth_CliImpl
    : public CSimpleAuth_CliBase
{
    public:
    typedef CSimpleAuth_CliBase super;
    CSimpleAuth_CliImpl( const IConfigDb* pCfg ) :
        super::virtbase( pCfg ), super( pCfg )
    { SetClassId( clsid(CSimpleAuth_CliImpl ) ); }

    gint32 CreateStmSkel(
        InterfPtr& pIf ) override;
    
    gint32 OnPreStart(
        IEventSink* pCallback ) override;
};

class CSimpleAuth_ChannelCli
    : public CRpcStreamChannelCli
{
    public:
    typedef CRpcStreamChannelCli super;
    CSimpleAuth_ChannelCli(
        const IConfigDb* pCfg ) :
        super::virtbase( pCfg ), super( pCfg )
    { SetClassId( clsid(
        CSimpleAuth_ChannelCli ) ); }
};

