// GENERATED BY RIDLC. MAKE SURE TO BACKUP BEFORE RE-COMPILING.
package org.rpcf.tests.asynctst;
import org.rpcf.rpcbase.*;
import java.util.Map;
import java.util.HashMap;
import java.lang.String;
import java.nio.ByteBuffer;
import java.util.concurrent.Semaphore;

public class AsyncTestcli extends AsyncTestclibase
{
    public Semaphore m_sem = new Semaphore(0);
    public AsyncTestcli( ObjPtr pIoMgr,
        String strDesc, String strSvrObj )
    { super( pIoMgr, strDesc, strSvrObj ); }
    
    public void onLongWaitNoParamComplete(Object oContext, int iRet) {
        this.m_sem.release();
        if (RC.SUCCEEDED(iRet)) {
            rpcbase.JavaOutputMsg("LongWaitNoParam complete successfully");
        } else {
            rpcbase.JavaOutputMsg("LongWaitNoParam failed with error " + iRet);
        }

    }
}
