#pragma once
enum EnumRidlClsid
{
    DECL_CLSID( CAttrExp ) = clsid( ClassFactoryStart ) + 40,
    DECL_CLSID( CAttrExps ),
    DECL_CLSID( CPrimeType ),
    DECL_CLSID( CArrayType ),
    DECL_CLSID( CMapType ),
    DECL_CLSID( CStructRef ),
    DECL_CLSID( CFieldDecl ),
    DECL_CLSID( CFieldList ),
    DECL_CLSID( CStructDecl ),
    DECL_CLSID( CFormalArg ),
    DECL_CLSID( CArgList ),
    DECL_CLSID( CMethodDecl ),
    DECL_CLSID( CMethodDecls ),
    DECL_CLSID( CInterfaceDecl ),
    DECL_CLSID( CInterfRef ),
    DECL_CLSID( CInterfRefs ),
    DECL_CLSID( CServiceDecl ),
    DECL_CLSID( CStatements ),
    DECL_CLSID( CAliasList ),
    DECL_CLSID( CTypedefDecl ),
    DECL_CLSID( CAppName ),
};
