#include <string>
#include <map>
enum EnumToken
{
    tok_struct=0x128,
    tok_interf,
    tok_service,
    /*types */
    tok_string,
    tok_uint64,
    tok_int64,
    tok_uint32,
    tok_int32,
    tok_uint16,
    tok_int16,
    tok_float,
    tok_double,
    tok_byte,
    tok_bool,
    tok_bytearr,
    tok_array,
    tok_map,
    tok_objptr,
    /*attribues*/
    tok_async,
    tok_asyncp,
    tok_asyncs,
    tok_return,
    tok_stream,
    tok_serial,
    tok_timeout,
    tok_rtpath,
    tok_ssl,
    tok_websock,
    tok_compres,
    tok_auth,
    /*literals*/
    tok_ident,
    tok_fltval,
    tok_dblval,
    tok_intval,
    tok_strval,
    tok_byval,
    tok_boolval,
};

extern std::map< std::string, EnumToken >
g_mapKeywords = {
    { "struct", tok_struct }, 
    { "interface", tok_interf }, 
    { "string", tok_string }, 
    { "uint64", tok_uint64 }, 
    { "int64", tok_int64 }, 
    { "uint32", tok_uint32 }, 
    { "int32", tok_int32 }, 
    { "uint16", tok_uint16 }, 
    { "int16", tok_int16 }, 
    { "float", tok_float }, 
    { "double", tok_double }, 
    { "byte", tok_byte },
    { "bool", tok_bool },
    { "bytearray", tok_bytearr },
    { "array", tok_array },
    { "map", tok_map },
    { "ObjPtr", tok_objptr },
    { "async", tok_async },
    { "async_p", tok_asyncp },
    { "async_s", tok_asyncs },
    { "returns", tok_return },
    { "stream", tok_stream },
    { "serial", tok_serial },
    { "timeout", tok_timeout },
    { "rtpath", tok_rtpath },
    { "ssl", tok_ssl },
    { "websock", tok_websock },
    { "compression", tok_compres },
    { "auth", tok_auth },
    { "service", tok_service },
};

