#include <string>
#include <map>
enum EnumToken
{
    tokInvalid = 0,
    tokStruct = 1,
    tokInterf,
    tokString,
    tokUint64,
    tokInt64,
    tokUint32,
    tokInt32,
    tokUint16,
    tokInt16,
    tokFloat,
    tokDouble,
    tokByte,
    tokBool,
    tokBytearr,
    tokArray,
    tokMap,
    tokObjPtr,
    tokLbrace,
    tokRbrace,
    tokSColon,
    tokLbrack,
    tokRbrack,
    tokAsync,
    tokAsyncp,
    tokAsyncs,
    tokReturn,
    tokComma,
    tokStream,
    tokSerial,
    tokTimeout,
    tokRtpath,
    tokSsl,
    tokWebsock,
    tokCompres,
    tokAuth,
    tokIdent,
    tokFloatVal,
    tokIntVal,
    tokStrVal,
    tokService,
    tokEqual,
    tokLParen,
    tokRParen,
    tokLangle,
    tokRangle,
};

extern std::map< std::string, EnumToken >
g_mapTokens = {
    { "struct", tokStruct }, 
    { "interface", tokStruct }, 
    { "string", tokString }, 
    { "uint64", tokUint64 }, 
    { "int64", tokInt64 }, 
    { "uint32", tokUint32 }, 
    { "int32", tokInt32 }, 
    { "uint16", tokUint16 }, 
    { "int16", tokInt16 }, 
    { "float", tokFloat }, 
    { "double", tokDouble }, 
    { "byte", tokByte },
    { "bool", tokBool },
    { "bytearray", tokBytearr },
    { "array", tokArray },
    { "map", tokMap },
    { "ObjPtr", tokObjPtr },
    { "async", tokAsync },
    { "async_p", tokAsyncp },
    { "async_s", tokAsyncs },
    { "return", tokReturn },
    { "stream", tokStream },
    { "serial", tokSerial },
    { "timeout", tokTimeout },
    { "rtpath", tokRtpath },
    { "ssl", tokSsl },
    { "websock", tokWebsock },
    { "compression", tokCompres },
    { "auth", tokAuth },
    { "service", tokService },
};

