#include <string>
#include <map>
enum EnumToken
{
    tokInvalid = 1,
    tokLParen='(',
    tokRParen=')',
    tokComma=',',
    tokSColon=';',
    tokLangle='<',
    tokEqual='=',
    tokRangle='>',
    tokLbrack='[',
    tokRbrack=']',
    tokLbrace='{',
    tokRbrace='}',
    tokStruct=0x128,
    tokInterf,
    tokService,
    /*types */
    tokString,
    tokUint64,
    tokInt64,
    tokUint32,
    tokInt32,
    tokUint16,
    tokInt16,
    tokFloat,
    tokDouble,
    tokByte,
    tokBool,
    tokBytearr,
    tokArray,
    tokMap,
    tokObjPtr,
    /*attribues*/
    tokAsync,
    tokAsyncp,
    tokAsyncs,
    tokReturn,
    tokStream,
    tokSerial,
    tokTimeout,
    tokRtpath,
    tokSsl,
    tokWebsock,
    tokCompres,
    tokAuth,
    /*literals*/
    tokIdent,
    tokFltVal,
    tokDblVal,
    tokIntVal,
    tokStrVal,
    tokByVal,
    tokBoolVal,
};

extern std::map< std::string, EnumToken >
g_mapTokens = {
    { "struct", tokStruct }, 
    { "interface", tokStruct }, 
    { "string", tokString }, 
    { "uint64", tokUint64 }, 
    { "int64", tokInt64 }, 
    { "uint32", tokUint32 }, 
    { "int32", tokInt32 }, 
    { "uint16", tokUint16 }, 
    { "int16", tokInt16 }, 
    { "float", tokFloat }, 
    { "double", tokDouble }, 
    { "byte", tokByte },
    { "bool", tokBool },
    { "bytearray", tokBytearr },
    { "array", tokArray },
    { "map", tokMap },
    { "ObjPtr", tokObjPtr },
    { "async", tokAsync },
    { "async_p", tokAsyncp },
    { "async_s", tokAsyncs },
    { "returns", tokReturn },
    { "stream", tokStream },
    { "serial", tokSerial },
    { "timeout", tokTimeout },
    { "rtpath", tokRtpath },
    { "ssl", tokSsl },
    { "websock", tokWebsock },
    { "compression", tokCompres },
    { "auth", tokAuth },
    { "service", tokService },
};

