// GENERATED BY RIDLC, MAKE SURE TO BACKUP BEFORE RUNNING RIDLC AGAIN
// Copyright (C) 2024  zhiming <woodhead99@gmail.com>
// This program can be distributed under the terms of the GNU GPLv3.
// ridlc -s -O . ../../../katest.ridl 
#pragma once
#include "katest.h"

#include "IKeepAlivesvr.h"

#define Clsid_CKeepAlive_SvrSkel_Base Clsid_Invalid

DECLARE_AGGREGATED_SKEL_SERVER(
    CKeepAlive_SvrSkel_Base,
    CStatCountersServerSkel,
    IIKeepAlive_SImpl );

class CKeepAlive_SvrSkel :
    public CKeepAlive_SvrSkel_Base
{
    public:
    typedef CKeepAlive_SvrSkel_Base super;
    CKeepAlive_SvrSkel( const IConfigDb* pCfg ):
        super::virtbase( pCfg ), super( pCfg )
    { SetClassId( clsid( CKeepAlive_SvrSkel ) ); }

    gint32 InvokeUserMethod(
        IConfigDb* pParams,
        IEventSink* pCallback ) override
    {
        CRpcServices* pSvc = nullptr;
        if( !IsRfcEnabled() )
        {
            if( m_pQpsTask.IsEmpty() )
                pSvc = this->GetStreamIf();
            else
                pSvc = this;
            gint32 ret = pSvc->AllocReqToken();
            if( ERROR( ret ) )
                return ret;
        }
        return super::InvokeUserMethod(
            pParams, pCallback );
    }
};

#define Clsid_CKeepAlive_SvrBase    Clsid_Invalid

DECLARE_AGGREGATED_SERVER(
    CKeepAlive_SvrBase,
    CStatCounters_SvrBase,
    IIKeepAlive_SvrApi,
    CFastRpcServerBase );

class CKeepAlive_SvrImpl
    : public CKeepAlive_SvrBase
{
    public:
    typedef CKeepAlive_SvrBase super;
    CKeepAlive_SvrImpl( const IConfigDb* pCfg ) :
        super::virtbase( pCfg ), super( pCfg )
    { SetClassId( clsid(CKeepAlive_SvrImpl ) ); }

    gint32 OnPostStart(
        IEventSink* pCallback ) override
    {
        TaskletPtr pTask = GetUpdateTokenTask();
        StartQpsTask( pTask );
        if( !pTask.IsEmpty() )
            AllocReqToken();
        return super::OnPostStart( pCallback );
    }

    gint32 OnPreStop(
        IEventSink* pCallback ) override
    {
        StopQpsTask();
        return super::OnPreStop( pCallback );
    }

    gint32 LongWaitCb(
        IEventSink*, IConfigDb* pReqCtx_,
        const std::string& i0 );

    // IKeepAlive
    virtual gint32 LongWait(
        IConfigDb* pReqCtx_,
        const std::string& i0 /*[ In ]*/,
        std::string& i0r /*[ Out ]*/ );
    
    // RPC Async Req Cancel Handler
    // Rewrite this method to release the resources
    gint32 OnLongWaitCanceled(
        IConfigDb* pReqCtx,
        gint32 iRet,
        const std::string& i0 /*[ In ]*/ );
    gint32 CreateStmSkel(
        HANDLE, guint32, InterfPtr& ) override;
    
    gint32 OnPreStart(
        IEventSink* pCallback ) override;
};

class CKeepAlive_ChannelSvr
    : public CRpcStreamChannelSvr
{
    public:
    typedef CRpcStreamChannelSvr super;
    CKeepAlive_ChannelSvr(
        const IConfigDb* pCfg ) :
        super::virtbase( pCfg ), super( pCfg )
    { SetClassId( clsid(
        CKeepAlive_ChannelSvr ) ); }
};

