# GENERATED BY RIDLC, MAKE SURE TO BACKUP BEFORE RUNNING RIDLC AGAIN
# Copyright (C) 2025  zhiming <woodhead99@gmail.com>
# This program can be distributed under the terms of the GNU GPLv3.
# ridlc --server -m thermometer -psO . ../../hellowld.ridl 
from typing import Tuple
from rpcf.rpcbase import *
from rpcf.proxy import *
from seribase import CSerialBase
from seribase import Variant
from HelloWorldstructs import *
import errno

class IIHelloWorld_SvrImpl :

    _ifName_ = "IHelloWorld"
    '''
    Synchronous request handler wrapper,
    which will deserialize the incoming parameters,
    call the actual request handler, and return the
    serialized response. It does not accept
    STATUS_PENDING on handler return. 
    '''
    def EchoWrapper( self,
        callback : cpp.ObjPtr, buf : bytearray
        ) -> Tuple[ int, list ] :
        
        oReqCtx_ = PyReqContext()
        oReqCtx_.oCallback = callback
        offset = 0
        listArgs = [ oReqCtx_, ]
        osb = CSerialBase( self )
        
        ret = osb.DeserialString( buf, offset )
        if ret[ 0 ] is None :
            return [ -errno.EBADMSG, None ]
        listArgs.append( ret[ 0 ] )
        
        targetMethod = self.GetMethod(
            "IHelloWorld", "Echo" )
        if targetMethod is None :
            return [ -errno.EFAULT, None ]
        ret = self.InvokeCallback(
            targetMethod, listArgs )
        bPending = ( ret[ 0 ] ==
            ErrorCode.STATUS_PENDING )
        if bPending :
            return [ -errno.EINVAL, [] ]
        if ret[ 0 ] < 0 :
            return [ ret[ 0 ], [] ]
        
        listResp = ret[ 1 ]
        buf = bytearray()
        iRet = ret[ 0 ]
        ret = 0
        while True:
            osb.SerialString( buf, listResp[0] )
            break
            
        return [ iRet, [ buf, ] ]
        
    
    
