# GENERATED BY RIDLC, MAKE SURE TO BACKUP BEFORE RUNNING RIDLC AGAIN
# Copyright (C) 2025  zhiming <woodhead99@gmail.com>
# This program can be distributed under the terms of the GNU GPLv3.
# ridlc --server -m thermometer -psO . ../../hellowld.ridl 
from rpcf.proxy import PyRpcServices
from seribase import CSerialBase
from seribase import Variant
import errno

