# GENERATED BY RIDLC, MAKE SURE TO BACKUP BEFORE RUNNING RIDLC AGAIN
# Copyright (C) 2025  zhiming <woodhead99@gmail.com>
# This program can be distributed under the terms of the GNU GPLv3.
# ridlc --server -m thermometer -psO . ../../hellowld.ridl 
from typing import Tuple
from rpcf.rpcbase import *
from rpcf.proxy import *
from seribase import CSerialBase
from seribase import Variant
from HelloWorldstructs import *
import errno

from HelloWorldSvcsvrbase import *
class CIHelloWorldsvr( IIHelloWorld_SvrImpl ):

    '''
    Synchronous request handler
    '''
    def Echo( self, oReqCtx : PyReqContext,
        strText : str
        ) -> Tuple[ int, list ] :
        '''
        the response parameters includes
        strResp : str
        '''
        #Implement this method here
        return [ ErrorCode.ERROR_NOT_IMPL, None ]
        
    
class CHelloWorldSvcServer(
    CIHelloWorldsvr,
    PyRpcServer ) :
    def __init__( self, pIoMgr, strDesc, strObjName ) :
        PyRpcServer.__init__( self,
            pIoMgr, strDesc, strObjName )
