# GENERATED BY RIDLC, MAKE SURE TO BACKUP BEFORE RUNNING RIDLC AGAIN
# Copyright (C) 2025  zhiming <woodhead99@gmail.com>
# This program can be distributed under the terms of the GNU GPLv3.
# ridlc --server -m thermometer -psO . ../../hellowld.ridl 
from typing import Tuple
from rpcf.rpcbase import *
from rpcf.proxy import *
from seribase import CSerialBase
from seribase import Variant
from HelloWorldstructs import *
import errno

from HelloWorldSvcsvr import CHelloWorldSvcServer
from appmancli import maincli as amc
from appmancli import appmonstructs as ams
import os
import time
from datetime import datetime

# we are using pymodbus library for modbus access.
from pymodbus.client import ModbusSerialClient

import signal
bExit = False
def SigHandler( signum, frame ):
    global bExit
    bExit = True

def Open485() :
    try:
        # /dev/ttyUSB0 is device our modbus
        # themometer connects. make sure to grant
        # read/write privilidge to this file.
        client = ModbusSerialClient(method='rtu',
            port='/dev/ttyUSB0',
            baudrate=9600,
            timeout=3,
            parity='N',
            stopbits=1,
            bytesize=8)
    except Exception as err: 
        print(err)
        client = None
    return client

def MainEntrySvr() :
    ret = 0
    signal.signal( signal.SIGINT, SigHandler)
    params=dict()
    params[ 'ModName' ] = 'HelloWorldsvr'
    params[ 'LogModName' ] = 'thermometer'
    oContext = PyRpcContext( params )
    with oContext as ctx:
        if ctx.status < 0:
            ret = ctx.status
            print( os.getpid(),
                "Error start PyRpcContext %d" % ret )
            return ret
        
        print( "start to work here..." )
        strPath_ = os.path.dirname( os.path.realpath( __file__) )
        strPath_ += '/HelloWorlddesc.json'
        oServer_HelloWorldSvc = CHelloWorldSvcServer( ctx.pIoMgr,
            strPath_, 'HelloWorldSvc' )
        ret = oServer_HelloWorldSvc.GetError()
        if ret < 0 :
            return ret
        
        with oServer_HelloWorldSvc as oServer:
            try:
                # tell the rpc-frmwrk monitor we
                # are the registered application
                # "thermometer"
                amc.StartAppManagercli( oServer,
                    oContext, "thermometer" )
                ret = mainsvr( oServer )
            except Exception as err:
                print( err )
            finally:
                amc.StopAppManagercli()
            
        print( "Server loop ended..." )
        oServer_HelloWorldSvc = None
    oContext = None
    return ret
    
def mainsvr( 
    oServer: CHelloWorldSvcServer ) -> int:
    '''
    make change to the following code
    snippet for your own purpose
    '''
    global bExit
    try:
        oAppMan = None
        while oAppMan is None:
            oAppMan = amc.GetAppManagercli()
            if oAppMan is None:
                print( "Failed to get appmancli" )
                time.sleep( 1 )
            else:
                break
                
        count = 0
        # open the thermometer device on RS485
        client = Open485()
        if client is None:
            print( "Failed to connect to RS485 device" )
            return -1
        connection = client.connect()
        if not connection:
            print( "Unable to connect to RS485 device" )
            return -1
        while ( cpp.stateConnected ==
            oServer.oInst.GetState() ):
            time.sleep( 1 )
            if bExit or amc.IsExit():
                break
            if count % 60 == 0:
                # read both the temperature and
                # humidity registers in one read
                result = client.read_holding_registers(
                    address=0, count=2, slave=1)
                if not result.isError():
                    arrValues=[]
                    oVal = Variant()
                    fval = result.registers[0]/10
                    oVal.SetFloat( fval )
                    temp = ams.KeyValue()
                    temp.strKey = "temperature"
                    temp.oValue = oVal
                    arrValues.append( temp )
                    oVal2 = Variant()
                    oVal2.SetFloat(
                        result.registers[1]/10 )
                    hum = ams.KeyValue()
                    hum.strKey = "humidity"
                    hum.oValue = oVal2
                    arrValues.append( hum )
                    # report the temperature to
                    # the rpc-frmwrk monitor.
                    ret = oAppMan.SetPointValues(
                        "thermometer", arrValues )
                    if ret[ 0 ] < 0:
                        print( f"Error SetPointValues {ret[0]}" )
                    else:
                        now = datetime.now()
                        print( now.strftime( "%Y-%m-%d %H:%M:%S" ) ) 
                        print( "updated the setpoint values ", fval )

                else:
                    print("Error reading register")
            count += 1

    except Exception as err:
        print( err )
    finally:
        if not client is None:
            client.close()

    return 0
    
if __name__ == '__main__' :
    ret = MainEntrySvr()
    quit( -ret )
