# Generated by RIDLC, make sure to backup before recompile
# ridlc -spf -O . ../../../../examples/hellowld.ridl 
import sys
from rpcf import iolib
from rpcf import serijson
import errno
from rpcf.proxy import ErrorCode as Err
from typing import Union, Tuple, Optional
from HelloWorldstructs import *
from ifimpl import *
class CIHelloWorldsvr( IIHelloWorld_SvrImpl ):
    '''
    Synchronous request handler
    within which to run the business logic.
    Returning Err.STATUS_PENDING for an
    asynchronous operation and returning other
    error code will complete the request. if the
    method returns STATUS_PENDING, make sure to
    call "self.EchoCompleteCb" later to
    complete the request. Otherwise, the client
    will get a timeout error. The return value is a
    list, with the first element as error code and
    the second element as a list of the response
    parameters.
    '''
    def Echo( self, reqId : object,
        strText : str
        ) -> Tuple[ int, list ] :
        #Implement this method here
        return [ 0, [ strText ] ]
        
    
class CHelloWorldSvcServer(
    CIHelloWorldsvr ) :
    def __init__( self, strSvcPoint : str, num : int ) :
        if num is None:
            num = 0
        error = 0
        self.m_strPath = strSvcPoint
        reqFile = strSvcPoint + "/jreq_" + str( num )
        self.m_reqFp = open( reqFile, "rb" )
        respFile = strSvcPoint + "/jrsp_" + str( num )
        self.m_respFp = open( respFile, "wb" )
        
    def sendResp( self, oResp : object ) -> int:
        return iolib.sendResp( self.m_respFp, oResp )
    
    def sendEvent( self, oEvent : object ) -> int:
        return iolib.sendEvent( self.m_respFp, oEvent )
    
    def recvReq( self ) -> Tuple[ int, object ]:
        return iolib.recvReq( self.m_reqFp )
    
    def getReqFp( self ) ->  object:
        return self.m_reqFp
    
    def OnKeepAlive( self, reqId : object ) -> int:
        if reqId is None:
            return -errno.EINVAL
        oResp = dict()
        oResp[ "RequestId" ] = reqId
        oResp[ "Method" ] = "OnKeepAlive"
        oResp[ "Interface" ] = "IInterfaceServer"
        oResp[ "MessageType" ] = "evt"
        return self.sendEvent( oResp )
    
    def DispatchMsg( self, oReq : dict ):
        try:
            if "IHelloWorld" == oReq[ "Interface" ] :
                IIHelloWorld_SvrImpl.DispatchIfMsg( self, oReq )
                return
            if "IInterfaceServer" == oReq[ "Interface" ] and "UserCancelRequest" == oReq[ "Method" ] :
                reqId = oReq[ "RequestId" ]
                oParams = oReq[ "Parameters" ]
                reqIdToCancel = oParams[ "RequestId" ]
                self.UserCancelRequest( reqId, reqIdToCancel )
                return
            
        except Exception as err:
            print( err )
            return
        
    def UserCancelRequest( self, reqId : object,
        reqIdToCancel : object ) -> int:
        # change this function for customized behavor
        print( "request", reqIdToCancel, " is canceled" )
        oParams = dict()
        oParams[ "RequestId" ] = reqIdToCancel
        oResp = BuildReqHeader( reqId,
            "UserCancelRequest",
            "IInterfaceServer",
            0, False, True )
        oResp[ "Parameters" ] = oParams
        return self.sendResp( oResp )
    
