#!/bin/bash
if grep 'debian' /etc/os-release; then
    force="t"
else
    force="f"
fi
if [ -f /usr/lib/rpcf/oinit*.whl ]; then
    if [[ "$force" == "t" ]]; then
        option="--break-system-packages"
    else
        option=""
    fi
    pip3 install ${option} /usr/lib/rpcf/oinit*.whl 
fi
