// GENERATED BY RIDLC. MAKE SURE TO BACKUP BEFORE RE-COMPILING.
package org.rpcf.tests.actcancel;
import org.rpcf.rpcbase.*;
import java.util.Map;
import java.util.HashMap;
import java.lang.String;
import java.nio.ByteBuffer;

import java.util.concurrent.TimeUnit;
public class maincli
{
    public static JavaRpcContext m_oCtx;
    public static String getDescPath( String strName )
    {
        String strDescPath =
            maincli.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        String strDescPath2 = strDescPath + "/org/rpcf/tests/actcancel/" + strName;
        java.io.File oFile = new java.io.File( strDescPath2 );
        if( oFile.isFile() )
            return strDescPath2;
        strDescPath += "/" + strName;
        oFile = new java.io.File( strDescPath );
        if( oFile.isFile() )
            return strDescPath;
        return "";
    }
    public static void main( String[] args )
    {
        m_oCtx = JavaRpcContext.createProxy(); 
        if( m_oCtx == null )
            System.exit( RC.EFAULT );
        
        String strDescPath =
            getDescPath( "actcanceldesc.json" );
        if( strDescPath.isEmpty() )
            System.exit( RC.ENOENT );
        // create the service object
        ActiveCancelcli oSvcCli = new ActiveCancelcli(
            m_oCtx.getIoMgr(), 
            strDescPath,
            "ActiveCancel" );

        // check if there are errors
        if( RC.ERROR( oSvcCli.getError() ) )
            System.exit( -oSvcCli.getError() );
        
        // start the proxy
        int ret = oSvcCli.start();
        if( RC.ERROR( ret ) )
            System.exit( -ret );
        
        do{
            // test remote server is not online
            while( oSvcCli.getState() == RC.stateRecovery )
            try{
                TimeUnit.SECONDS.sleep(1);
            }
            catch( InterruptedException e ){};
            
            if( oSvcCli.getState() != RC.stateConnected )
            { ret = RC.ERROR_STATE;break;}

            String i0 = "hello, actcancel server";
            // request something from the server
            JRetVal jret = oSvcCli.LongWait( "haha",
                i0 );
            if( jret.ERROR() )
                break;
            if(jret.isPending())
            {
                long iTaskId = jret.getTaskId();
                try {
                    TimeUnit.SECONDS.sleep(3);
                }catch (InterruptedException e){
                }
                ret = oSvcCli.getInst().CancelRequest(iTaskId);
                if( RC.SUCCEEDED(ret))
                    rpcbase.JavaOutputMsg("Canceled the request " + iTaskId);
                else if( ret == -RC.ENOENT)
                    rpcbase.JavaOutputMsg("Did not find the request to cancel " + iTaskId);
                else
                    rpcbase.JavaOutputMsg(
                            "failed to cancel the request " + iTaskId +
                                    "with error " + ret);

            }
            else
            {
                rpcbase.JavaOutputMsg("weird, 'LongWait' complete successfully");
            }

        }while( false );

        oSvcCli.stop();
        m_oCtx.stop();
        return;
    }
}
