#Generated by RIDLC, make sure to backup before running RIDLC again
from typing import Tuple
from rpcf.rpcbase import *
from rpcf.proxy import *
from seribase import CSerialBase
from HelloWorldstructs import *
import errno

from HelloWorldSvcsvrbase import *
class CIHelloWorldsvr( IIHelloWorld_SvrImpl ):

    '''
    Synchronous request handler
    '''
    def Echo( self, oReqCtx : PyReqContext,
        strText : str
        ) -> Tuple[ int, list ] :
        '''
        the response parameters includes
        strResp : str
        '''
        #Implement this method here
        print("proxy says '" + strText + "'")
        strResp = "Hello, Proxy!"
        return [ ErrorCode.STATUS_SUCCESS, [strResp] ]
        
    
class CHelloWorldSvcServer(
    CIHelloWorldsvr,
    PyRpcServer ) :
    def __init__( self, pIoMgr, strDesc, strObjName ) :
        PyRpcServer.__init__( self,
            pIoMgr, strDesc, strObjName )
