// GENERATED BY RIDLC. MAKE SURE TO BACKUP BEFORE RE-COMPILING.
package org.rpcf.tests.evtest;

import org.rpcf.rpcbase.JavaRpcContext;
import org.rpcf.rpcbase.RC;

import java.util.concurrent.TimeUnit;
public class maincli
{
    public static JavaRpcContext m_oCtx;
    public static String getDescPath( String strName )
    {
        String strDescPath =
            maincli.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        String strDescPath2 = strDescPath + "/org/rpcf/tests/evtest/" + strName;
        java.io.File oFile = new java.io.File( strDescPath2 );
        if( oFile.isFile() )
            return strDescPath2;
        strDescPath += "/" + strName;
        oFile = new java.io.File( strDescPath );
        if( oFile.isFile() )
            return strDescPath;
        return "";
    }
    public static void main( String[] args )
    {
        m_oCtx = JavaRpcContext.createProxy(); 
        if( m_oCtx == null )
            System.exit( RC.EFAULT );
        
        String strDescPath =
            getDescPath( "evtestdesc.json" );
        if( strDescPath.isEmpty() )
            System.exit( RC.ENOENT );
        // create the service object
        EventTestcli oSvcCli = new EventTestcli(
            m_oCtx.getIoMgr(), 
            strDescPath,
            "EventTest" );

        // check if there are errors
        if( RC.ERROR( oSvcCli.getError() ) )
            System.exit( -oSvcCli.getError() );
        
        // start the proxy
        int ret = oSvcCli.start();
        if( RC.ERROR( ret ) )
            System.exit( -ret );
        
        do{
            // test remote server is not online
            while( oSvcCli.getState() == RC.stateRecovery )
            try{
                TimeUnit.SECONDS.sleep(1);
            }
            catch( InterruptedException e ){};
            
            if( oSvcCli.getState() != RC.stateConnected )
            { ret = RC.ERROR_STATE;break;}
            
            /*
             *Just waiting and events will 
             *be handled in the background
             */
             while( oSvcCli.getState() == RC.stateConnected )
             try{
                 TimeUnit.SECONDS.sleep(1);
             } catch (InterruptedException e) {
             }

        }while( false );

        oSvcCli.stop();
        m_oCtx.stop();
        System.exit( -ret );
    }
}