// Generated by ridlc
// ridlc -s -O . ../../asynctst.ridl 
// Your task is to implement the following classes
// to get your rpc server work
#pragma once
#include "asynctst.h"

#define Clsid_CAsyncTest_CliBase    Clsid_Invalid

DECLARE_AGGREGATED_PROXY(
    CAsyncTest_CliBase,
    IIAsyncTest_CliApi,
    CFastRpcProxyBase );

class CAsyncTest_CliImpl
    : public CAsyncTest_CliBase
{
    sem_t m_semWait;
    gint32 m_iError = STATUS_SUCCESS;

    public:
    typedef CAsyncTest_CliBase super;
    CAsyncTest_CliImpl( const IConfigDb* pCfg ) :
        super::virtbase( pCfg ), super( pCfg )
    {
        SetClassId( clsid(CAsyncTest_CliImpl ) );
        Sem_Init( &m_semWait, 0, 0 );
    }

    inline void NotifyComplete()
    { Sem_Wait( &m_semWait ); }

    inline void WaitForComplete()
    { Sem_Post( &m_semWait ); }

    inline void SetError( gint32 iError )
    { m_iError = iError; }

    inline gint32 GetError() const
    { return m_iError; }

    // RPC Async Req Callback
    gint32 LongWaitNoParamCallback(
        IConfigDb* context, 
        gint32 iRet ) override;
    gint32 CreateStmSkel(
        InterfPtr& pIf ) override;
    
    gint32 OnPreStart(
        IEventSink* pCallback ) override;
};

class CAsyncTest_ChannelCli
    : public CRpcStreamChannelCli
{
    public:
    typedef CRpcStreamChannelCli super;
    CAsyncTest_ChannelCli(
        const IConfigDb* pCfg ) :
        super::virtbase( pCfg ), super( pCfg )
    { SetClassId( clsid(
        CAsyncTest_ChannelCli ) ); }
};

