// GENERATED BY RIDLC, MAKE SURE TO BACKUP BEFORE RUNNING RIDLC AGAIN
// Copyright (C) 2024  zhiming <woodhead99@gmail.com>
// This program can be distributed under the terms of the GNU GPLv3.
// ridlc -O . ../oaproxy.ridl 
// Implement the following methods
// to get the RPC proxy/server work
#include "rpc.h"
using namespace rpcf;
#include "oa2check.h"
#include "OA2proxycli.h"

// OAuth2Proxy Proxy
/* Async Req Complete Handler*/
gint32 COA2proxy_CliImpl::IsTokenValidCallback(
    IConfigDb* context, gint32 iRet,
    bool bValid /*[ In ]*/ )
{
    // TODO: Process the server response here
    // return code ignored
    return 0;
}

/* Async Req Complete Handler*/
gint32 COA2proxy_CliImpl::GetUserInfoCallback(
    IConfigDb* context, gint32 iRet,
    USER_INFO& ui /*[ In ]*/ )
{
    // TODO: Process the server response here
    // return code ignored
    return 0;
}

/* Async Req Complete Handler*/
gint32 COA2proxy_CliImpl::RevokeUserCallback(
    IConfigDb* context, gint32 iRet )
{
    // TODO: Process the server response here
    // return code ignored
    return 0;
}

