// GENERATED BY RIDLC, MAKE SURE TO BACKUP BEFORE RUNNING RIDLC AGAIN
// Copyright (C) 2025  zhiming <woodhead99@gmail.com>
// This program can be distributed under the terms of the GNU GPLv3.
// ../../../../ridl/.libs/ridlc --services=AppMonitor --odesc_url=https://192.168.1.3/rpcf -sJO . ../../../../monitor/appmon/appmon.ridl 
const { CConfigDb2 } = require( '/usr/local/lib/rpcf/jslib/combase/configdb' );
const { messageType } = require( '/usr/local/lib/rpcf/jslib/dbusmsg/constants' );
const { randomInt, ERROR, Int32Value, USER_METHOD } = require( '/usr/local/lib/rpcf/jslib/combase/defines' );
const {EnumClsid, errno, EnumPropId, EnumCallFlags, EnumTypeId, EnumSeriProto} = require( '/usr/local/lib/rpcf/jslib/combase/enums' );
const {CSerialBase, Variant} = require( '/usr/local/lib/rpcf/jslib/combase/seribase' );
const {CFastRpcProxy} = require( '/usr/local/lib/rpcf/jslib/ipc/fastrpc' )
const {Buffer} = require( 'buffer' );
const { DBusIfName, DBusDestination2, DBusObjPath } = require( '/usr/local/lib/rpcf/jslib/rpc/dmsg' );
const { KeyValue, } = require( './appmonstructs' );
const { CAppMonitorclibase } = require ( './AppMonitorclibase' )
class CAppMonitor_CliImpl extends CAppMonitorclibase
{
    constructor( oIoMgr, strObjDescPath, strObjName, oParams )
    {
        super( oIoMgr, strObjDescPath, strObjName, oParams );
        this.OnDataReceived = this.OnDataReceivedImpl.bind( this );
        this.OnStmClosed = this.OnStmClosedImpl.bind( this );
        this.m_setAppBaseLine = new Set( );
        //this.m_setAppBaseLine.add( 'appmonsvr1' );
        //this.m_setAppBaseLine.add( 'timer1' );
        //this.m_setAppBaseLine.add( 'loggersvr1' );
    }

    // The following are callbacks and event handlers
    // which need to be filled out by you
    
    // IAppStore::ListAppsCallback
    // request callback
    ListAppsCallback( oContext, ret,
        arrApps // (String)
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.ListApps
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
        if( oContext.oListAppCb )
            oContext.oListAppCb( oContext, ret, arrApps );
    }

    // IAppStore::ListPointsCallback
    // request callback
    ListPointsCallback( oContext, ret,
        arrPoints // (String)
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.ListPoints
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::ListAttributesCallback
    // request callback
    ListAttributesCallback( oContext, ret,
        arrAttributes // (String)
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.ListAttributes
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::SetPointValueCallback
    // request callback
    SetPointValueCallback( oContext, ret )
    {
        // add code here
        // 'oContext' is the parameter passed to this.SetPointValue
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::GetPointValueCallback
    // request callback
    GetPointValueCallback( oContext, ret,
        rvalue // Variant
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.GetPointValue
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
        if( oContext.oGetPvCb )
            oContext.oGetPvCb( oContext, ret, rvalue );
    }

    // IAppStore::SetLargePointValueCallback
    // request callback
    SetLargePointValueCallback( oContext, ret )
    {
        // add code here
        // 'oContext' is the parameter passed to this.SetLargePointValue
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::GetLargePointValueCallback
    // request callback
    GetLargePointValueCallback( oContext, ret,
        value // Uint8Array
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.GetLargePointValue
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
        if( oContext.oGetLpvCb )
            oContext.oGetLpvCb( oContext, ret, value )
    }

    // IAppStore::SubscribeStreamPointCallback
    // request callback
    SubscribeStreamPointCallback( oContext, ret )
    {
        // add code here
        // 'oContext' is the parameter passed to this.SubscribeStreamPoint
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::SetAttrValueCallback
    // request callback
    SetAttrValueCallback( oContext, ret )
    {
        // add code here
        // 'oContext' is the parameter passed to this.SetAttrValue
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::GetAttrValueCallback
    // request callback
    GetAttrValueCallback( oContext, ret,
        rvalue // Variant
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.GetAttrValue
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::SetPointValuesCallback
    // request callback
    SetPointValuesCallback( oContext, ret )
    {
        // add code here
        // 'oContext' is the parameter passed to this.SetPointValues
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    // IAppStore::GetPointValuesCallback
    // request callback
    GetPointValuesCallback( oContext, ret,
        arrKeyVals // (KeyValue)
    )
    {
        if( oContext.oGetPvsCb )
            oContext.oGetPvsCb( oContext, ret, arrKeyVals );
    }

    // IAppStore::OnPointChanged
    // event handler
    OnPointChanged(
        strPtPath, // String
        value // Variant
    )
    {
        // add code here
        if( globalThis.OnPointChanged )
            globalThis.OnPointChanged( strPtPath, value );
    }

    // IAppStore::OnPointsChanged
    // event handler
    OnPointsChanged(
        arrKVs // (KeyValue)
    )
    {
        // add code here
        console.log("OnPointsChanged:", arrKVs);
    }

    // IAppStoreEx::IsAppOnlineCallback
    // request callback
    IsAppOnlineCallback( oContext, ret,
        strOnlineApps // (String)
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.IsAppOnline
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
        if( oContext.oIsAppOnlineCb )
            oContext.oIsAppOnlineCb( oContext, ret, strOnlineApps )
    }

    // IAppStoreEx::GetPointDescCallback
    // request callback
    GetPointDescCallback( oContext, ret,
        mapPtDescs // [String,ObjPtr]
    )
    {
        // add code here
        // 'oContext' is the parameter passed to this.GetPointDesc
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
        if( oContext.oGetPtDescCb )
            oContext.oGetPtDescCb( oContext, ret, mapPtDescs )
    }

    // IAppMonitor::RegisterListenerCallback
    // request callback
    RegisterListenerCallback( oContext, ret )
    {
        // add code here
        // 'oContext' is the parameter passed to this.RegisterListener
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
        if( oContext.oRegListenerCb )
            oContext.oRegListenerCb( oContext, ret )
    }

    // IAppMonitor::RemoveListenerCallback
    // request callback
    RemoveListenerCallback( oContext, ret )
    {
        // add code here
        // 'oContext' is the parameter passed to this.RemoveListener
        // 'ret' is the status code of the request
        // if ret == errno.STATUS_SUCCESS, the following parameters are valid response from the server
        // if ret < 0, the following parameters are undefined
    }

    /**
    * callback called when data arrives from the stream channel `hStream`
    * @param {number} hStream the stream channel the data comes in 
    * @param {Buffer} oBuf the payload in Uint8Array or Buffer
    */
    OnDataReceivedImpl( hStream, oBuf )
    {
        // add code here
        // to handle the incoming byte stream
    }

    /**
    * callback called when the stream channel `hStream` is closed
    * @param {number} hStream the stream channel closed 
    */
    OnStmClosedImpl( hStream )
    {
        // add code here
        // to do some cleanup work if necessary
    }
}

exports.CAppMonitor_CliImpl = CAppMonitor_CliImpl;
