#FROM --platform=linux/armhf dtcooper/raspberrypi-os:bookworm as armhf_build
FROM --platform=linux/armhf debian:bookworm as armhf_build
MAINTAINER woodhead99@gmail.com
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata locales apt-utils
SHELL ["/bin/bash", "-c"]

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

#install the kerberos servers and client
ADD ./initkrb5.sh /root
RUN apt-get install -qq krb5-kdc krb5-admin-server krb5-user
#setup the kdc and kadmind and start the servers
CMD bash /root/initkrb5.sh || exit 1
#login with principal zhiming
CMD kinit -k -t /etc/krb5.keytab zhiming || exit 2

RUN apt-get install -y --fix-missing gcc g++ python3 python3-dev python3-pip python3-build flex bison \
libtool shtool automake autoconf autotools-dev make dbus dbus-bin python3-venv \
libdbus-1-dev libjsoncpp-dev libkrb5-dev \
liblz4-dev lz4 openssl libssl-dev libcppunit-dev \
libfuse3-dev fuse3 bash net-tools procps swig cmake attr \
libcommons-cli-java curl figlet python3-urwid gettext
RUN apt-get install -y default-jdk-headless || apt-get install -y openjdk-8-jdk-headless

# Create our clean sandbox environment 
RUN python3 -m venv /opt/venv

# Inject the environment paths globally for all future layers and execution tasks
ENV PATH="/opt/venv/bin:$PATH"

# ubuntu 22.04's official version of nodejs is outdated, lets install node 20 from nodejs'
# site instead.
ENV NVM_DIR="/root/.nvm"

RUN success="false";for i in $(seq 1 100);do \
    if ! curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash; then sleep 1; continue; fi; \
    [ -s "${NVM_DIR}/nvm.sh" ] && . "${NVM_DIR}/nvm.sh"; \ 
    if nvm install 20 && node -v && nvm list; then success="true";break;fi;\
    done; \
    if [[ "$success" == "false" ]]; then echo -e "\e[33mcannot download nvm and nodejs..., disable JS support\e[0m"; touch ${HOME}/nojs; fi

RUN pip install --upgrade pip && pip install sip

RUN apt-get -y install git devscripts debhelper expect vim screen tmux iputils-ping;
RUN cd ${HOME};for i in $(seq 1 100);do if git clone 'https://github.com/zhiming99/GmSSL.git'; then break; fi;done
RUN cd ${HOME};cd ./GmSSL;mkdir build;cd build;cmake ..;make;make install
RUN apt-get -y install python3-wheel python3-numpy || pip3 install wheel numpy
RUN if [ ! -f ${HOME}/nojs ]; then . ${NVM_DIR}/nvm.sh; npm -g install assert browserify buffer exports long lz4 process put safe-buffer stream xxhashjs xxhash webpack webpack-cli minify vm events crypto-browserify stream-browserify;fi
RUN cd ${HOME};for i in $(seq 1 100);do if git clone 'https://github.com/zhiming99/rpc-frmwrk.git';then break;fi;done
RUN cd ${HOME}/rpc-frmwrk && libtoolize && aclocal && autoreconf -vfi && \
automake --add-missing && autoconf; echo `pwd`;ls -l `pwd`
RUN if [ -f ${HOME}/nojs ]; then opt='--disable-js'; else . ${NVM_DIR}/nvm.sh; fi; cd ${HOME}/rpc-frmwrk && bash cfgsel -r $opt && make -j4 && make install; \
    echo 'export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rpcf' >> ${HOME}/.bashrc
ADD ./testcfgs/mincfg.json /root
RUN python3 /usr/local/bin/rpcf/rpcfgnui.py ${HOME}/mincfg.json
RUN if [ -f ${HOME}/nojs ]; then echo -e "\e[33mrpc-frmwrk is built without JS support \e[0m"; rm -f ${HOME}/nojs; else cd ${HOME}/rpc-frmwrk; figlet -cm 60 'RPC-FRMWRK ROCKS !';fi
# uncomment the following to start the tests
#dbus-run-session bash tools/runtest.sh 2 & \
#dbus-run-session bash tools/runtest.sh 1

