#please make sure to run 'make dist' first at the root of the source tree
FROM ubuntu
MAINTAINER @PACKAGE_BUGREPORT@
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get install -y gcc g++ python3 python3-dev python3-pip flex bison \
libtool shtool automake autoconf autotools-dev make dbus libdbus-1-3 \
libdbus-1-dev libjsoncpp1 libjsoncpp-dev libkrb5-3 libkrb5-dev liblz4-1 \
liblz4-dev lz4 openssl libssl1.1 libssl-dev libcppunit-1.15-0 libcppunit-dev \
bash net-tools procps;pip3 install numpy wheel
RUN apt-get -y install sip5-tools || apt-get -y install sip-dev python3-sip python3-sip-dev || true
ADD ../@PACKAGE@-@VERSION@.tar.gz /root/
RUN cd /root/@PACKAGE@-@VERSION@;/bin/sh
/root/@PACKAGE@-@VERSION@/configure;make;make install;echo 'export
LD_LIBRARY_PATH=@prefix@/lib:@prefix@/lib/@PACKAGE@'>>/root/.bashrc
RUN dbus-run-session bash /root/@PACKAGE@-@VERSION@/tools/runtest.sh 2 &
RUN dbus-run-session bash /root/@PACKAGE@-@VERSION@/tools/runtest.sh 1

