#!/usr/bin/env python3
import json
import os
import sys 
from shutil import move
from copy import deepcopy
from urllib.parse import urlparse
from typing import Dict
import errno
from updcfg import *
from updwscfg import *

import getopt, sys

def usage():
    print( "Usage: python3 rpcfgnui.py <init file>" )
    print( "\t<init file> can be generated by <SaveAs>" )
    print( "\tfrom rpcfg.py on a host with GUI" )

import getopt
def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h" )
    except getopt.GetoptError as err:
        # print help information and exit:
        print(err)  # will print something like "option -a not recognized"
        usage()
        sys.exit(-errno.EINVAL)

    for o, a in opts:
        if o == "-h" :
            usage()
            sys.exit( 0 )
        else:
            assert False, "unhandled option"
 
    if len( args ) == 0 :
        usage()
        sys.exit( -errno.EINVAL )
    

    ret = 0
    initFile = args[ 0 ]

    try:
        ret = Update_InitCfg( initFile, None )
        if not IsFeatureEnabled( "openssl" ):
            return ret

        ret = ConfigWebServer( initFile )
        if ret < 0:
            print( "Error failed to config web server " + str(ret))
            ret = 0

    except Exception as err:
        text = "Failed to update the config files:" + str( err )
        exc_type, exc_obj, exc_tb = sys.exc_info()
        fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
        second_text = "@" + fname + ":" + str(exc_tb.tb_lineno)
        print( text, second_text )
        ret = -errno.EFAULT

    return ret

if __name__ == "__main__":
    main()
