// GENERATED BY RIDLC. MAKE SURE TO BACKUP BEFORE RE-COMPILING.
package org.rpcf.tests.katest;

import org.rpcf.rpcbase.JRetVal;
import org.rpcf.rpcbase.JavaRpcContext;
import org.rpcf.rpcbase.RC;
import org.rpcf.rpcbase.rpcbase;

import java.util.concurrent.TimeUnit;
public class maincli
{
    public static JavaRpcContext m_oCtx;
    public static String getDescPath( String strName )
    {
        String strDescPath =
            maincli.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        String strDescPath2 = strDescPath + "/org/rpcf/tests/katest/" + strName;
        java.io.File oFile = new java.io.File( strDescPath2 );
        if( oFile.isFile() )
            return strDescPath2;
        strDescPath += "/" + strName;
        oFile = new java.io.File( strDescPath );
        if( oFile.isFile() )
            return strDescPath;
        return "";
    }

    public static void main( String[] args )
    {
        m_oCtx = JavaRpcContext.createProxy(); 
        if( m_oCtx == null )
            System.exit( RC.EFAULT );

        String strDescPath =
            getDescPath( "katestdesc.json" );
        if( strDescPath.isEmpty() )
            System.exit( RC.ENOENT );
        // create the service object
        KeepAlivecli oSvcCli = new KeepAlivecli(
            m_oCtx.getIoMgr(), 
            strDescPath,
            "KeepAlive" );

        // check if there are errors
        if( RC.ERROR( oSvcCli.getError() ) )
            System.exit( -oSvcCli.getError() );
        
        // start the proxy
        int ret = oSvcCli.start();
        if( RC.ERROR( ret ) )
            System.exit( -ret );
        
        do{
            // test remote server is not online
            while( oSvcCli.getState() == RC.stateRecovery )
            try{
                TimeUnit.SECONDS.sleep(1);
            }
            catch( InterruptedException ignored){};
            
            if( oSvcCli.getState() != RC.stateConnected )
            { ret = RC.ERROR_STATE;break;}

            // request something from the server
            String i0 = "hello, katest";
            JRetVal jret = oSvcCli.LongWait(
                    i0 );
            if( jret.ERROR() )
            {
                rpcbase.JavaOutputMsg(
                        "LongWait failed with error " + jret.getError());
                ret = jret.getError();
                break;
            }
            else
            {
                String i0r = (String)jret.getAt(0);
                rpcbase.JavaOutputMsg(
                        "LongWait completed with response " + i0r);
                ret = 0;
                break;

            }
            
        }while( false );

        oSvcCli.stop();
        m_oCtx.stop();
        System.exit( -ret );
    }
}